### ISSUE TITLE
ModuleNotFoundError: No module named 'demucs.htdemucs'

### ISSUE THREAD

**Issue by youyang-617** [ZFTurbo/MVSEP-MDX23-music-separation-model#10]
I cloned the repository directly and installed the dependencies using pip install -r 'requirements.txt', but when I tried to run it, I encountered the error ModuleNotFoundError: No module named 'demucs.htdemucs'. Is there an issue with the decmus or torchaudio versions that I should use? If so, which versions should I use? Thank you!

**Comment by cheerjam1991** [comment]
same issue, have you figured it out?

**Comment by cheerjam1991** [comment]
Thank you！ resolved！

> Try to install one more time:
> 
> `pip install demucs`
