### ISSUE TITLE
Question about multiple inferences in decums model

### ISSUE THREAD

**Issue by owlwang** [ZFTurbo/MVSEP-MDX23-music-separation-model#27]
First of all, thank you for creating this impressive project! The work you've done is truly remarkable.

I had a question while looking through the codebase. I noticed that the decums model is called twice during the inference process. 

```python
vocals_demucs = 0.5 * apply_model(model, audio, shifts=shifts, overlap=overlap)[0][3].cpu().numpy()

vocals_demucs += 0.5 * -apply_model(model, -audio, shifts=shifts, overlap=overlap)[0][3].cpu().numpy()
```

Is there a specific reason that two separate calls are required? I'm curious if this is some sort of optimization trick or if there is another technical motivation behind it.

Thanks again for building such an amazing tool!

**Comment by ZFTurbo** [comment]
This technique is called "Test Time Augmentation". We predict on original audio and mirrored audio and then average the result. It usually gives slightly better and less noisy result.

**Comment by owlwang** [comment]
Thanks!
