### ISSUE TITLE
[❓] Is it a mistake to use 96,000 Hz for input audio?

### ISSUE THREAD

**Issue by E7admin** [ZFTurbo/MVSEP-MDX23-music-separation-model#38]
(PS. I used mvsep.com for my work.)

Hi MVSEP Fam.

I was wondering if the sampling rate affects the separation results? My input audio is 96,000 Hz, do I need to downsample it to 44,100 Hz before uploading the file? (I see that the datasets we are using is 44,100 Hz.)

**Comment by happyTonakai** [comment]
It will automatically resample your audio to 44100 Hz.
https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/blob/b60ff879e83539fad3064920d387e69cc7cfb811/inference.py#L834
