### ISSUE TITLE
Training Guide

### ISSUE THREAD

**Issue by james-clarke-audio** [ZFTurbo/MVSEP-MDX23-music-separation-model#40]
Hi,

I would like to train the model from scratch and supplement the stated dataset with additional audio.  I am finding it difficult to understand how you configure HTDemuxs for training.  Any advice or steps would be helpful

thanks

**Comment by ZFTurbo** [comment]
Hello. You can use this code:
https://github.com/ZFTurbo/Music-Source-Separation-Training
