### ISSUE TITLE
How to exclude instrum/instrum2 from separation?

### ISSUE THREAD

**Issue by andivax** [ZFTurbo/MVSEP-MDX23-music-separation-model#41]
Hi!
Thank you for the great tool!
After separation I've got 4 instrument groups (drums, bass, other and voc) + instrum and instrum2.
How to disable separation (or creation) of that "instrum" and "instrum2" instrumentals?

**Comment by ZFTurbo** [comment]
Delete lines from 854 until 865 in `inference.py`:
https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/blob/main/inference.py#L854

**Comment by andivax** [comment]
nope. it causes crash after BAT file launch

**Comment by ZFTurbo** [comment]
Make sure you delete them completely without leaving tabs or spaces.

**Comment by andivax** [comment]
yup, I've removed these lines entirely. But app don't even start. Crash

**Comment by ZFTurbo** [comment]
Try this:
[inference.zip](https://github.com/user-attachments/files/16895262/inference.zip)

**Comment by andivax** [comment]
Thank you, Sir! Working!
But "generate only vocals/instrumental" option exports only vocals now. Which is logical actually )
